Debug CodeQL++++

diff --git a/.github/workflows/CI-SCANN.yml b/.github/workflows/CI-SCANN.yml
--- a/.github/workflows/CI-SCANN.yml
+++ b/.github/workflows/CI-SCANN.yml
@@ -42,6 +42,7 @@ jobs:
 
   code-scanning:
     runs-on: ubuntu-latest
+    needs: build-and-test
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -97,7 +98,10 @@ jobs:
     runs-on: ubuntu-latest
     needs: code-scanning
     steps:
-      - name: Download Reports
+      - name: Create Reports Directory
+        run: mkdir -p reports
+
+      - name: Download SpotBugs Report
         uses: actions/download-artifact@v3
         with:
           name: spotbugs-report
@@ -121,15 +125,12 @@ jobs:
           name: codeql-results
           path: reports/codeql
 
-      - name: Create Reports Directory
-        run: mkdir -p reports
-
       - name: Move Reports
         run: |
-          mv reports/spotbugs/target/spotbugs/spotbugs.xml reports/spotbugs-report.xml
-          mv reports/checkstyle/target/checkstyle-result.xml reports/checkstyle-report.xml
-          mv reports/pmd/target/pmd.xml reports/pmd-report.xml
-          mv reports/codeql/codeql-results.sarif reports/codeql-results.sarif
+          mv reports/spotbugs/spotbugs.xml reports/spotbugs-report.xml || echo "SpotBugs report not found."
+          mv reports/checkstyle/checkstyle-result.xml reports/checkstyle-report.xml || echo "Checkstyle report not found."
+          mv reports/pmd/pmd.xml reports/pmd-report.xml || echo "PMD report not found."
+          mv reports/codeql/codeql-results.sarif reports/codeql-results.sarif || echo "CodeQL results not found."
 
       - name: Upload All Reports as Artifacts
         uses: actions/upload-artifact@v3
